name: npm ci

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.12.1"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install & Build
        run: |
          cd docs
          npm ci
          npm run build
